  
---
- name: minishift project create
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Get a list of all Services in the myapp namespace.
      community.kubernetes.k8s_info:
        kind: Service
        namespace: testminishift
      register: myapp_services
